<div class="page-header">
    <h1>Latest Incidents</h1>
</div>

<?php
    foreach($this->latestIncidents as $incident):
        echo '<div class="latest-incident">';
        echo '<div class="heading"><a href="/incident/read/'.$incident->id.'">Incident #'.$incident->id.' <span class="quiet">('.$incident->date_occurred.')</span></a></div>';
        echo '<div class="body">';
        echo '<div class="body"><p>'.$incident->explanation.'</p></div>';
        echo '</div>';
        echo '</div>';
    endforeach;
?>